// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficHunt.Infrastructure.Persistence;

#nullable disable

namespace TrafficHunt.Infrastructure.Migrations
{
    [DbContext(typeof(TrafficHuntDbContext))]
    partial class TrafficHuntDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OutreachInstructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryProblem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QualificationRules")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReplyInstructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValueProposition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.CampaignKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Keyword")
                        .IsUnique();

                    b.ToTable("CampaignKeywords");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.CampaignProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignProblems");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorChannelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<string>("YouTubeCommentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("VideoId", "YouTubeCommentId")
                        .IsUnique();

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Prospect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasRelevantProblem")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IntentScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsTargetAudience")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastContactedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PainPoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeChannelId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeProfileUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IntentScore");

                    b.HasIndex("CampaignId", "CommentId")
                        .IsUnique();

                    b.ToTable("Prospects");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.ReplyCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("MinDelaySeconds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RepliesFailed")
                        .HasColumnType("int");

                    b.Property<int>("RepliesPending")
                        .HasColumnType("int");

                    b.Property<int>("RepliesSent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("ReplyCampaigns");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.ReplyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("MessageSent")
                        .HasColumnType("longtext");

                    b.Property<int>("ProspectId")
                        .HasColumnType("int");

                    b.Property<int>("ReplyCampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProspectId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("ReplyCampaignId", "Status");

                    b.ToTable("ReplyRecords");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.ReplyTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ReplyCampaignId")
                        .HasColumnType("int");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReplyCampaignId");

                    b.ToTable("ReplyTemplates");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "YouTubeVideoId")
                        .IsUnique();

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.CampaignKeyword", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Keywords")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.CampaignProblem", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Problems")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Comment", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.Video", "Video")
                        .WithMany("Comments")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Prospect", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Prospects")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.ReplyCampaign", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.ReplyRecord", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.Prospect", "Prospect")
                        .WithMany()
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficHunt.Domain.Entities.ReplyCampaign", "ReplyCampaign")
                        .WithMany("ReplyRecords")
                        .HasForeignKey("ReplyCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficHunt.Domain.Entities.ReplyTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId");

                    b.Navigation("Prospect");

                    b.Navigation("ReplyCampaign");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.ReplyTemplate", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.ReplyCampaign", "ReplyCampaign")
                        .WithMany("Templates")
                        .HasForeignKey("ReplyCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplyCampaign");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Video", b =>
                {
                    b.HasOne("TrafficHunt.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("Problems");

                    b.Navigation("Prospects");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.ReplyCampaign", b =>
                {
                    b.Navigation("ReplyRecords");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("TrafficHunt.Domain.Entities.Video", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
