using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace TrafficHunt.Web.Logging;

/// <summary>
/// Records every inbound HTTP request into the <see cref="LogStore"/> so the
/// operator can see all UI traffic live (method, path, status, elapsed).
///
/// Register as the FIRST middleware (outermost) so exception-handling middleware
/// downstream can still finalize the response status before we snapshot it.
/// Self-polling endpoints and static assets are skipped to keep the feed focused.
/// </summary>
public sealed class RequestLoggingMiddleware
{
    private readonly RequestDelegate _next;
    private readonly LogStore _store;

    // High-frequency endpoints that would otherwise flood the live feed with
    // noise generated by the log viewer / dashboard themselves.
    private static readonly HashSet<string> _excludedPrefixes = new(StringComparer.OrdinalIgnoreCase)
    {
        "/logs/recent",
        "/hangfire"
    };

    private static readonly string[] _staticSuffixes =
        { ".css", ".js", ".map", ".png", ".jpg", ".jpeg", ".svg", ".gif", ".ico", ".woff2", ".woff" };

    public RequestLoggingMiddleware(RequestDelegate next, LogStore store)
    {
        _next = next;
        _store = store;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        var path = context.Request.Path.Value ?? "/";

        if (IsExcluded(path))
        {
            await _next(context);
            return;
        }

        var qs = context.Request.QueryString.HasValue ? context.Request.QueryString.Value ?? "" : "";
        var method = context.Request.Method;

        var sw = Stopwatch.StartNew();
        int? status = null;
        Exception? err = null;

        try
        {
            await _next(context);
            status = context.Response.StatusCode;
        }
        catch (Exception ex)
        {
            err = ex;
            status = context.Response.StatusCode; // may be 0 when nothing was written yet
            throw; // let downstream exception handlers (or Kestrel) finalize the response
        }
        finally
        {
            // Only record once per request; the /logs/recent endpoint is excluded above.
            sw.Stop();

            var level = status >= 500 ? LogLevel.Error
                : status >= 400 ? LogLevel.Warning
                : LogLevel.Information;

            var message = err != null
                ? $"Request failed: {err.GetType().Name}: {err.Message}"
                : status >= 400 ? $"HTTP {(int)status}" : "OK";

            _store.Append(new LogEntry
            {
                Level = level,
                Category = "HTTP Request",
                Message = message,
                RequestMethod = method,
                RequestPath = path + qs,
                StatusCode = status,
                DurationMs = sw.ElapsedMilliseconds,
                CorrelationId = context.TraceIdentifier
            });
        }
    }

    private static bool IsExcluded(string path)
    {
        var lower = path.ToLowerInvariant();
        foreach (var prefix in _excludedPrefixes)
            if (lower.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                return true;

        if (lower.StartsWith("/lib/", StringComparison.Ordinal) ||
            lower.StartsWith("/css/", StringComparison.Ordinal) ||
            lower.StartsWith("/js/", StringComparison.Ordinal))
            return true;

        foreach (var ext in _staticSuffixes)
            if (lower.EndsWith(ext, StringComparison.OrdinalIgnoreCase))
                return true;

        return false;
    }
}
